### ISSUE TITLE
Use Nova v3.17.0 cant delete, popup modal not show

### ISSUE THREAD

**Issue by forzadraco** [emotality/summernote-nova#1]
after removing         "emotality/summernote-nova": "^1.0", 
the modal delete confirmation is works

**Comment by emotality** [comment]
Sorry for late reply, summer holiday and Christmas etc.

Yes, sorry, this is a known issue but I'm not so clued up with vuejs to be able to fix it myself.

If someone can do a PR, that would be appreciated!

**Comment by emotality** [comment]
Archiving this repo.
